### PR TITLE
A footer component added

### PR DESCRIPTION
**Pull request by gitshashwat**
Related to https://github.com/Usateid/Hacktoberfest-Vue-2/issues/1#issue-716578181

### CODE REVIEW

**Comment by Usateid** [comment]
Thanks for you pull request :)
Your component is great but can be improved more ! 
For example ? Computed can be written without the double quotes "" because it is not a string !
And the return of the year function can be written simply without the parsing to string

Like This!
  computed: {
    year() {
      return new Date().getFullYear()
    }
  }
  
Other Tips:
a component MUST have always a name ! It's really important !!
Thank you for pushing the package-lock.json, i completely forgot it ! 
That why I've pushed it to the main branch. Just delete it for your project and merge that file from the main branch again

Thank you :)

**Comment by gitshashwat** [comment]
Sure, I'll improve the code and raise a PR again. Thanks for the tips! :) 
For "a component MUST always have a name ! It's really important !!", I did name the component to Footer.vue. Did I misunderstand something here?

**Comment by Usateid** [comment]
> Sure, I'll improve the code and raise a PR again. Thanks for the tips! :)
> For "a component MUST always have a name ! It's really important !!", I did name the component to Footer.vue. Did I misunderstand something here?

That's is how you've saved the component inside your project, but a component needs always a name ! Give a look at the 'Hello World' components. Here's the structure:
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  }
}

Do you see the name :) ?

**Comment by gitshashwat** [comment]
Oh, thanks a lot! I'll make sure I remember these tips. I'll raise a clean improved PR later. :)

**Pull request closed without merging**
